export const COMPANY_GET_ALL = '[COMPANY] COMPANY_GET_ALL';
export const COMPANY_GET_ONE = '[COMPANY] COMPANY_GET_ONE';
export const COMPANY_CREATE  = '[COMPANY] COMPANY_CREATE';
export const COMPANY_UPDATE  = '[COMPANY] COMPANY_UPDATE';